use std::env;
use std::fs;
use std::path::Path;

/// Stable discovery order for bundled themes.
const DISCOVERY_ORDER: &[&str] = &[
    "default-dark",
    "default-light",
    "tokyo-night",
    "tokyo-storm",
    "tokyo-moon",
    "tokyo-day",
    "everforest-dark",
    "everforest-light",
    "ayu-dark",
    "ayu-mirage",
    "ayu-light",
    "catppuccin-latte",
    "catppuccin-frappe",
    "catppuccin-macchiato",
    "catppuccin-mocha",
    "gruvbox-dark",
    "gruvbox-light",
    "kanagawa-wave",
    "kanagawa-dragon",
    "kanagawa-lotus",
    "nord",
    "nord-light",
    "one-dark",
    "one-light",
    "matrix",
];

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets_dir = Path::new(&manifest_dir).join("../../assets/themes");
    let out_dir = env::var("OUT_DIR").unwrap();

    let mut load_arms = String::new();
    let mut entry_lines = String::new();

    for id in DISCOVERY_ORDER {
        let path = assets_dir.join(format!("{id}.json"));
        if !path.exists() {
            panic!("missing bundled theme file: {}", path.display());
        }

        let content = fs::read_to_string(&path).unwrap();
        let theme: serde_json::Value = serde_json::from_str(&content)
            .unwrap_or_else(|e| panic!("invalid theme JSON {}: {e}", path.display()));
        let display_name = theme["name"]
            .as_str()
            .unwrap_or_else(|| panic!("theme {} missing name field", id));
        let appearance = theme["appearance"]
            .as_str()
            .unwrap_or_else(|| panic!("theme {} missing appearance field", id));
        let appearance_rust = match appearance {
            "dark" => "Appearance::Dark",
            "light" => "Appearance::Light",
            other => panic!("theme {} has invalid appearance: {other}", id),
        };

        load_arms.push_str(&format!(
            r#"        "{id}" => Some(Theme::load_from_str(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../assets/themes/{id}.json"))).expect("bundled theme {id} should be valid")),
"#
        ));

        entry_lines.push_str(&format!(
            r#"        ThemeEntry {{ name: "{id}".into(), display_name: "{display_name}".into(), appearance: {appearance_rust} }},
"#
        ));

        println!("cargo:rerun-if-changed={}", path.display());
    }

    let generated = format!(
        r#"// @generated by build.rs — do not edit

pub fn load_bundled(name: &str) -> Option<Theme> {{
    match name {{
{load_arms}
        _ => None,
    }}
}}

pub fn bundled_theme_entries() -> Vec<ThemeEntry> {{
    vec![
{entry_lines}
    ]
}}

pub fn is_bundled(name: &str) -> bool {{
    matches!(
        name,
{matches}
    )
}}
"#,
        load_arms = load_arms,
        entry_lines = entry_lines,
        matches = DISCOVERY_ORDER
            .iter()
            .map(|id| format!(r#"        "{id}""#))
            .collect::<Vec<_>>()
            .join(" |\n"),
    );

    fs::write(Path::new(&out_dir).join("bundled_themes.rs"), generated).unwrap();
}
